In [1]:
import os

import numpy as np
import tensorflow as tf

import config, music_model_vectorized

ROOT_PATH = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
conf = config.Config("single_instruments_type", ROOT_PATH)

batch_size = 2

2022-12-20 00:08:41.225534: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-20 00:08:41.327761: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-12-20 00:08:41.327775: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-12-20 00:08:41.796767: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-

In [2]:
model = music_model_vectorized.create_debugging_model(
    decoder_output_shape=[6144, 512],
    song_shape=[6143, 11]
)

model.compile(optimizer="adam")

In [3]:
dataset = tf.data.Dataset.load(conf.tf_data7dict_path)
dataset = dataset.batch(batch_size)

In [4]:
for item in dataset.take(1):
    songs = item[0][0]

In [5]:
scores = np.random.random((batch_size, 6144, 512))

In [6]:
def print_stuff(inputs):
    a, b = inputs
    tf.print(a, "-", b)
    print(a, "-", b)
    return a

mask = tf.vectorized_map(
            fn=print_stuff,
            elems=(
                tf.range(10), 
                tf.expand_dims([0, 1, 5, 7], axis=0)
            )
        )

print(mask)

Tensor("loop_body/GatherV2:0", shape=(), dtype=int32) - Tensor("loop_body/GatherV2_1:0", shape=(4,), dtype=int32)
0 - [0 1 5 7]
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [7]:
model((scores, songs))

{'type': <tf.Tensor: shape=(2, 6143, 8), dtype=float32, numpy=
 array([[[0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.7770673 , 0.2229327 , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.7136575 , 0.28634262, ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ]],
 
        [[0.        , 0.99999994, 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.7004479 , 0.29955205, ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.3740007 , 0.6259994 , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 1.