In [1]:
import os

import numpy as np
import tensorflow as tf

import config, music_model_vectorized

ROOT_PATH = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
conf = config.Config("single_instruments_type", ROOT_PATH)

batch_size = 2

2022-12-18 22:27:29.106627: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-18 22:27:29.806212: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-18 22:27:29.806313: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-18 22:27:29.806319: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nv

In [2]:
model = music_model_vectorized.create_debugging_model(
    decoder_output_shape=[6144, 512],
    song_shape=[6143, 11]
)

model.compile(optimizer="adam")


In [3]:
dataset = tf.data.Dataset.load(conf.tf_data7dict_path)
dataset = dataset.batch(batch_size)

In [4]:
for item in dataset.take(1):
    songs = item[0][0]

In [5]:
scores = np.random.random((batch_size, 6144, 512))

In [6]:
def print_stuff(inputs):
    a, b = inputs
    tf.print(a, "-", b)
    print(a, "-", b)
    return a

mask = tf.vectorized_map(
            fn=print_stuff,
            elems=(
                tf.range(10), 
                tf.expand_dims([0, 1, 5, 7], axis=0)
            )
        )

print(mask)

Tensor("loop_body/GatherV2:0", shape=(), dtype=int32) - Tensor("loop_body/GatherV2_1:0", shape=(4,), dtype=int32)
0 - [0 1 5 7]
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [7]:
model((scores, songs))

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


InvalidArgumentError: Exception encountered when calling layer 'masking_activation_layer' (type MaskingActivationLayer).

in user code:

    File "/home/franco/github/MusicGeneration/src/music_model_vectorized.py", line 688, in get_mask_for_one_elem_in_batch  *
        mask = tf.vectorized_map(

    InvalidArgumentError: Graph execution error:
    
    Detected at node 'strided_slice/pfor/TensorListConcatV2' defined at (most recent call last):
        File "/home/franco/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "/home/franco/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
          app.launch_new_instance()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/traitlets/config/application.py", line 985, in launch_instance
          app.start()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
          self.io_loop.start()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
          self.asyncio_loop.run_forever()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
          self._run_once()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
          handle._run()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
          self._context.run(self._callback, *self._args)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
          await self.process_one()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
          await dispatch(*args)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
          await result
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
          reply_content = await reply_content
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
          res = shell.run_cell(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
          return super().run_cell(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2940, in run_cell
          result = self._run_cell(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2995, in _run_cell
          return runner(coro)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
          coro.send(None)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3194, in run_cell_async
          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3373, in run_ast_nodes
          if await self.run_code(code, result, async_=asy):
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
          exec(code_obj, self.user_global_ns, self.user_ns)
        File "/tmp/ipykernel_30151/2616150909.py", line 1, in <module>
          model((scores, songs))
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/training.py", line 561, in __call__
          return super().__call__(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
          outputs = call_fn(inputs, *args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/functional.py", line 511, in call
          return self._run_internal_graph(inputs, training=training, mask=mask)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/functional.py", line 668, in _run_internal_graph
          outputs = node.layer(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
          outputs = call_fn(inputs, *args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/src/music_model_vectorized.py", line 716, in call
          masks = tf.map_fn(
        File "/home/franco/github/MusicGeneration/src/music_model_vectorized.py", line 688, in get_mask_for_one_elem_in_batch
          mask = tf.vectorized_map(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 198, in f
          warn=warn)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        [Previous line repeated 15 more times]
    Node: 'strided_slice/pfor/TensorListConcatV2'
    Detected at node 'strided_slice/pfor/TensorListConcatV2' defined at (most recent call last):
        File "/home/franco/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "/home/franco/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
          app.launch_new_instance()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/traitlets/config/application.py", line 985, in launch_instance
          app.start()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 712, in start
          self.io_loop.start()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
          self.asyncio_loop.run_forever()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
          self._run_once()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
          handle._run()
        File "/home/franco/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
          self._context.run(self._callback, *self._args)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
          await self.process_one()
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 499, in process_one
          await dispatch(*args)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
          await result
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 730, in execute_request
          reply_content = await reply_content
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 383, in do_execute
          res = shell.run_cell(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
          return super().run_cell(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2940, in run_cell
          result = self._run_cell(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2995, in _run_cell
          return runner(coro)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
          coro.send(None)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3194, in run_cell_async
          has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3373, in run_ast_nodes
          if await self.run_code(code, result, async_=asy):
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
          exec(code_obj, self.user_global_ns, self.user_ns)
        File "/tmp/ipykernel_30151/2616150909.py", line 1, in <module>
          model((scores, songs))
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/training.py", line 561, in __call__
          return super().__call__(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
          outputs = call_fn(inputs, *args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/functional.py", line 511, in call
          return self._run_internal_graph(inputs, training=training, mask=mask)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/functional.py", line 668, in _run_internal_graph
          outputs = node.layer(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
          outputs = call_fn(inputs, *args, **kwargs)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
          return fn(*args, **kwargs)
        File "/home/franco/github/MusicGeneration/src/music_model_vectorized.py", line 716, in call
          masks = tf.map_fn(
        File "/home/franco/github/MusicGeneration/src/music_model_vectorized.py", line 688, in get_mask_for_one_elem_in_batch
          mask = tf.vectorized_map(
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 198, in f
          warn=warn)
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        File "/home/franco/github/MusicGeneration/env/lib/python3.9/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 4483, in f
          [converter._convert_helper(x).t for x in func._func_graph_outputs])
        [Previous line repeated 15 more times]
    Node: 'strided_slice/pfor/TensorListConcatV2'
    2 root error(s) found.
      (0) INVALID_ARGUMENT:  All except the first dimension must be fully defined when concating an empty tensor list. element_shape: <unknown>
    	 [[{{node strided_slice/pfor/TensorListConcatV2}}]]
    	 [[loop_body/StatefulPartitionedCall/pfor/StatefulPartitionedCall/cond_1/pfor/PartitionedCall_1/cond_1/cond/pfor/PartitionedCall_1/cond_1/cond/cond/pfor/PartitionedCall_1/cond_1/cond/cond/cond_1/pfor/PartitionedCall/cond_1/cond/cond/cond_1/cond_2/pfor/PartitionedCall_1/cond_1/cond/cond/cond_1/cond_2/cond/pfor/Tile_1/_658]]
      (1) INVALID_ARGUMENT:  All except the first dimension must be fully defined when concating an empty tensor list. element_shape: <unknown>
    	 [[{{node strided_slice/pfor/TensorListConcatV2}}]]
    0 successful operations.
    0 derived errors ignored. [Op:__inference_f_24066]


Call arguments received by layer 'masking_activation_layer' (type MaskingActivationLayer):
  • inputs=['tf.Tensor(shape=(2, 6143, 11), dtype=int32)', ['tf.Tensor(shape=(2, 6143, 8), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 256), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 131), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 128), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 136), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 256), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 129), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 128), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 25), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 153), dtype=float32)', 'tf.Tensor(shape=(2, 6143, 49), dtype=float32)'], 'tf.Tensor(shape=(2, 6143, 8), dtype=float32)']
  • training=True

In [ ]:
model((scores, songs))

chosen_type 1
type1 second instrument called final return TensorShape([1391])
final return vector [1 0 0 ... 0 0 0]
chosen_type 027
chosen_type 1
chosen_type 3
min_measure_shape TensorShape([])
min_measure [0 0 0 ... 0 0 0]
chosen_type 456
027-1init TensorShape([1391])
type1 second instrument called final return TensorShape([1391])
final return vector [[1 0 0 ... 0 0 0]]
min_measure [0 0 0 ... 0 0 1]
measure_mask [[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
TensorShape([256])
TensorShape([131])
TensorShape([128])
TensorShape([136])
TensorShape([256])
TensorShape([129])
TensorShape([128])
TensorShape([25])
TensorShape([153])
TensorShape([49])
actual vectors
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 

{'type': <tf.Tensor: shape=(2, 6143, 8), dtype=float32, numpy=
 array([[[0.        , 1.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.19133557, 0.80866444, ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.2221901 , 0.77780986, ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 1.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 1.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 1.        ]],
 
        [[0.        , 1.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.10799571, 0.89200425, ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.16278827, 0.8372117 , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.